### ISSUE TITLE
failure to load the weight which you provide

### ISSUE THREAD

**Issue by KungFuPandaPro** [qcf-568/DocTamper#1]
![image](https://github.com/qcf-568/DocTamper/assets/67446107/16c3c7c6-db20-4eec-be5a-052da61970d5)

**Comment by qcf-568** [comment]
Hello,
Could you please try the colab notebook I provided?
https://colab.research.google.com/drive/1rWaSKy2Rsy5welyvj6FbzF01o2zv8ips?usp=sharing
