### ISSUE TITLE
self.swin = torch.load('swin_imagenet.pt')

### ISSUE THREAD

**Issue by 256-7421142** [qcf-568/DocTamper#11]
self.vph = torch.load('vph_imagenet.pt')
 self.swin = torch.load('swin_imagenet.pt')
 self.fph = FPH()
In line 294 of the dtd.py file, why is it not necessary to define self.vph = VPN() and self.swin = self.swin = SwinTransformerV2(), and how is from swins import * used in line 29, and why can't I debug any information on the self.swin variable.

**Comment by qcf-568** [comment]
The .pt files contain not only the model parameters but also the model structure, so  is it not necessary to define self.vph = VPN() and self.swin = self.swin = SwinTransformerV2().

**Comment by qcf-568** [comment]
The model's structure is fixed in .pt files, so can not debug any information on the self.swin variable.

**Comment by 256-7421142** [comment]
> The .pt files contain not only the model parameters but also the model structure, so is it not necessary to define self.vph = VPN() and self.swin = self.swin = SwinTransformerV2().
File "/mnt/data/experiments/DocTamper-main/models/eval_dtd.py", line 225, in <module>
    eval_net_dtd(model, test_data)
TypeError: expected Tensor as element 1 in argument 0, but got NoneType
When I run this code directly, I can finally get almost the same result as the paper, but when I debug the process, I get a typerror, why is that?
CUDA_VISIBLE_DEVICES=0 python eval_dtd.py --lmdb_name DocTamperV1-FCD --pth pths/dtd_doctamper.pth --minq 75

**Comment by qcf-568** [comment]
It seems that the datatype was wrong, I'm not sure which variable did you modified.

**Comment by 256-7421142** [comment]
> The model's structure is fixed in .pt files, so can not debug any information on the self.swin variable.

So why define class VPH in the dtd.py file, where is it called? Also what is the purpose of swins.py and from swins import *? Just load it, because I don't think it's used at runtime.

**Comment by qcf-568** [comment]
> So why define class VPH in the dtd.py file, where is it called? Also what is the purpose of swins.py and from swins import *? Just load it, because I don't think it's used at runtime.

The reason for all above is: If I do not do these, the program will report errors and stop running.
Even loading fixed structure from such .pt files, class definitions are necessary.

**Comment by SherlockHua1995** [comment]
hi @qcf-568 ，if I want to test the pretrained model under torch1.10.1,using the infer_sroie.py, the 
self.vph = torch.load('vph_imagenet.pt')
self.swin = torch.load('swin_imagenet.pt')
got error :
attributeerror:can't get attribute 'BasicLayer' on module __main__
Any advice?

**Comment by qcf-568** [comment]
@SherlockHua1995 the infer_sroie.py should be placed in the same dir of swin.py

**Comment by kshitij005** [comment]
Hi @qcf-568 ,

I am making flask api to load image and detect text tampering,
when I run image_test.py that you gave me in the same directory of swins.py i am still getting the same error,
File "app.py", line 12, in <module>
    from DocTamper.models.image_test import text_tampering_detection
  File "DS_PROJECTS/DOC_FRAUD/05. Api/DocTamper/models/image_test.py", line 32, in <module>
    model = seg_dtd("",2).to(device)
  File "DS_PROJECTS/DOC_FRAUD/05. Api/DocTamper/models/dtd.py", line 325, in __init__
    self.model = DTD(encoder_name=model_name, classes=n_class)
  File "DS_PROJECTS/DOC_FRAUD/05. Api/DocTamper/models/dtd.py", line 302, in __init__
    self.swin = torch.load(os.path.join(os.getcwd(), 'DocTamper', 'models','swin_imagenet.pt'))
  File "DS_PROJECTS/DOC_FRAUD/venv/lib/python3.8/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/DS_PROJECTS/DOC_FRAUD/venv/lib/python3.8/site-packages/torch/serialization.py", line 1046, in _load
    result = unpickler.load()
  File "DS_PROJECTS/DOC_FRAUD/venv/lib/python3.8/site-packages/torch/serialization.py", line 1039, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'BasicLayer' on <module '__main__' from 'app.py'>

I am new in this field, please could you help me with this error?

**Comment by qcf-568** [comment]
@kshitij005 This error can be solved by putting the swin.py into the same dir of your app.py
