### ISSUE TITLE
'rgb': np.clip(np.abs(dct),0,20)  why？

### ISSUE THREAD

**Issue by 256-7421142** [qcf-568/DocTamper#12]

**Comment by Mohamed-Dhouib** [comment]
Wondering the same thing !

**Comment by qcf-568** [comment]
Here are the answers:

**Comment by qcf-568** [comment]
1. Why use np.abs and np.clip: You can refer to the CAT-Netv2 paper. The most information of  DCT coef focuses on about the zero point, and the sign of them are not so useful. 2. Why clip to 20: the same as CAT-Netv2 for a fair comparison. 3. Why named as 'rgb': It inherited from the debug process, it's actually the dct coef.
