### ISSUE TITLE
can someone please explain how can i use the codes to check on a particular image 

### ISSUE THREAD

**Issue by naman01072002** [qcf-568/DocTamper#14]

**Comment by qcf-568** [comment]
Crop the whole image into patches, inference with the patches and combine the result. You can refer to L39~L137 of https://github.com/qcf-568/DocTamper/blob/main/models/tsroie/infer_sroie.py. It's notable that the provided models didn't consider the edge padding, I suggest fine-tuning them with patches with edge padding.
