### ISSUE TITLE
The image is not reopened after that last compression

### ISSUE THREAD

**Issue by Mohamed-Dhouib** [qcf-568/DocTamper#15]
https://github.com/qcf-568/DocTamper/blob/db5189013c9ab4ab4404b0a7a3e64f388dcde18b/dataloader.py#L76C23-L76C23
Hello, 
In the dataloader.py file, it appears that the image isn’t reopened after the final compression. This means that if there are three compressions, the image provided to the model has only undergone two compressions. However, the DCT coefficients and the quantization table are from the final compression, which is problematic. Could you clarify the reasoning behind this approach, or is this simply an oversight in the code?

**Comment by qcf-568** [comment]
It's simply an oversight in the code. Moreover, the last compression on the image itself has very limited influence on the performance and has no influence on the conclusion.
