### ISSUE TITLE
Why do you need to enter dct and qtable in the fph branch instead of just dct, what is the significance of qtable?

### ISSUE THREAD

**Issue by 256-7421142** [qcf-568/DocTamper#16]

**Comment by qcf-568** [comment]
The qtable can provide more information about the compression process, as well as the DCT coef before compression, thus can help towards a better performance. The inclusion of the qtable brings much more obvious improvement when image is compressed only once after tampering, e.g. the image in T-SROIE dataset.

**Comment by 256-7421142** [comment]
> The qtable can provide more information about the compression process, as well as the DCT coef before compression, thus can help towards a better performance. The inclusion of the qtable brings much more obvious improvement when image is compressed only once after tampering, e.g. the image in T-SROIE dataset.
But the dct coefficients returned by jpegio are not already compressed by the quantisation table? dct can enough represent the frequency characteristic
