### ISSUE TITLE
About doctamper

### ISSUE THREAD

**Issue by 256-7421142** [qcf-568/DocTamper#19]
doctamper数据集中都是被篡改过的？真实图像和篡改图像的比例是怎么样，是否有表示图像是篡改还是真实图像的标签呢？

**Comment by 256-7421142** [comment]
如果我想得到这个标签该怎么生成呢

**Comment by qcf-568** [comment]
出于版权保护及隐私保护需求，DocTamper仅提供篡改后的图像.
