### ISSUE TITLE
some variances VPH(nn.Module)   of   dtd.py do not exist, depths and self.dims.could you please add them?

### ISSUE THREAD

**Issue by KungFuPandaPro** [qcf-568/DocTamper#2]
![image](https://github.com/qcf-568/DocTamper/assets/67446107/c98bf8f8-4c9f-4f82-b4d4-5662a6dcc9f2)
![image](https://github.com/qcf-568/DocTamper/assets/67446107/bad3eb8e-2d43-4fd2-95c1-07fa57d58a27)

**Comment by KungFuPandaPro** [comment]
![image](https://github.com/qcf-568/DocTamper/assets/67446107/d6069dbd-a40a-45ed-a6c3-6c0b9febd52e)
self.norm0 and self.norm1

**Comment by qcf-568** [comment]
Yes, you can see these details by "print(torch.load('vph_imagenet.pt'))".

**Comment by KungFuPandaPro** [comment]
> Yes, you can see these details by "print(torch.load('vph_imagenet.pt'))".

ok,thank you ,could you please update the code?

**Comment by qcf-568** [comment]
I'm very busy now, I will update the code if they have bug.
