### ISSUE TITLE
两个embedding层的作用是什么呢

### ISSUE THREAD

**Issue by 256-7421142** [qcf-568/DocTamper#20]
self.obembed self.qtembed的的作用是什么呢

**Comment by 256-7421142** [comment]
> 分别是标准正交基编码DCT系数及可学习嵌入编码量化表

这个理论依据是什么呢

**Comment by qcf-568** [comment]
标准正交基编码嵌入：1、希望编码层能够对数字的大小及变化敏感，以捕捉块效应异常，所以用嵌入层；2、因为DCT系数矩阵里面不同的系数数值本身相互无关，比如1和2是完全独立的数字，所以用正交基；3、这些独立的系数地位平等，所以是标准正交基。
可学习量化嵌入：理论上可学习的嵌入比固定的更好，但DCT系数矩阵的分辨率比量化表大太多，所以DCT系数矩阵也用标准正交基会导致训练不稳定及过拟合。量化表只有64个像素，用可学习嵌入学到更合适的嵌入表征而又不容易出现上述问题。
