### ISSUE TITLE
AttributeError: 'GELU' object has no attribute 'approximate'

### ISSUE THREAD

**Issue by ayaan-mphasis** [qcf-568/DocTamper#22]
Hi, I am getting this issue while running eval_dtd.py. I have installed the given requirements.txt. Any idea why this might be happenig?

**Comment by qcf-568** [comment]
Hi, have you tried this colab-notebook? https://colab.research.google.com/drive/1rWaSKy2Rsy5welyvj6FbzF01o2zv8ips?usp=sharing

**Comment by Shaurya026** [comment]
That was caused by torch version mismatch 

You can use the same model with older torch version by using following code: 
```
def torchmodify(name) :
    a=name.split('.')
    for i,s in enumerate(a) :
        if s.isnumeric() :
            a[i]="_modules['"+s+"']"
    return '.'.join(a) 

# following executes the same mentioned above
for name, module in model.named_modules() :
    if isinstance(module,nn.GELU) :
        exec('model.'+torchmodify(name)+'=nn.GELU()')
``` 
where your `model` is the instantiated model object

**Comment by qcf-568** [comment]
Here is a solution for this, https://blog.csdn.net/A_Student10000/article/details/132403264
