### ISSUE TITLE
Inference on PNG images?

### ISSUE THREAD

**Issue by PhmHiu** [qcf-568/DocTamper#23]
Hi, I want to ask if the model can inference on PNG images instead of JPG, JPEG images

**Comment by qcf-568** [comment]
Hi, you can convert them to JPEG images with quality factors of 100.

**Comment by PhmHiu** [comment]
Do I need to reload the saved jpeg file or I can use directly the image load from png file

**Comment by qcf-568** [comment]
It's suggested reloading the saved jpeg file.
