### ISSUE TITLE
测试demo，文件缺失

### ISSUE THREAD

**Issue by bai-0829** [qcf-568/DocTamper#24]
你好，请问如果我想检测我自己的图片，运行哪个文件呢？还有一个问题是“sroie_test_1011.json”和“data.mdb lock.mdb”这三个文件在哪里下载呢？

**Comment by qcf-568** [comment]
切块推理并合并结果. 可以参考 L39~L137 of https://github.com/qcf-568/DocTamper/blob/main/models/tsroie/infer_sroie.py.
目前版本不支持截图且整图推理建议加有边缘padding的切块样本进行微调。

sroie_test_1011.json来自https://github.com/wangyuxin87/Tampered_sroie
data.mdb lock.mdb是来自DocTamper各个测试数据集的lmdb格式，需用教育邮箱申请相应数据集。

**Comment by bai-0829** [comment]
谢谢，在您的帮助下我现在已经将测试运行起来了，我还有两个小问题：
1. “infer_sroie.py”中似乎显示的是使用“dtd_sroie.pth”，您提供的这个权重训练了多少epoch呢，是否为最佳权重结果，还是说只是进行了少量的epoch来作为一个例子
2. 下载下来的权重文件有四个，其他三个权重文件是用来做什么或者是怎么得到的呢？
非常期待与感谢您的耐心回答

**Comment by qcf-568** [comment]
1、dtd_sroie.pth是用ImageNet参数初始化模型后仅在T-SROIE上训练400epoch，中间过程未进行动态验证，是否最佳不确定，应该是接近最佳。
2、dtd_doctamper是用来复现推理的，其为是用ImageNet参数初始化模型后仅在DocTamper训练集上训练10epoch。其他两个.pt文件分别是VPH及SwinTransformer的ImageNet预训练权重，训练阶段需要用它们初始化相应参数。

**Comment by bai-0829** [comment]
好的，感谢您的回答！
