### ISSUE TITLE
Regarding dataset access

### ISSUE THREAD

**Issue by Tasmay-Tibrewal** [qcf-568/DocTamper#25]
Respected Sir,
I am a student from IIT Kharagpur, India, working on a Problem Statement relating to fraud detection in medical invoices and bills. We have our competition starting today.  I had mailed you earlier regarding this but did not get any reply.

I urgently need access to the dataset.

Please provide me with the password to access the dataset. You can contact me at keshavtibrewal2@gmail.com.

**Comment by Tasmay-Tibrewal** [comment]
pls sir

**Comment by qcf-568** [comment]
Could you please resend the application with education email address instead of gmail.
