### ISSUE TITLE
full capacity

### ISSUE THREAD

**Issue by qiyuebobo** [qcf-568/DocTamper#26]
I encountered an issue with the training code I wrote: the memory usage kept increasing until it reached full capacity and stopped (around the 4th epoch), preventing the completion of multiple training iterations. 
For confidentiality purposes, could you please provide an email address so that I can privately send you this Python file?

**Comment by qcf-568** [comment]
I also encountered such question before, and I'm 100% sure it is a bug from the jpegio library. So I conducted the experiments on the server with big memory and saved checkpoints every epoch.

If you have any other questions about the training re-implement, you can send your files to 202221012612@mail.scut.edu.cn, I will help to check them.

**Comment by qiyuebobo** [comment]
thanks for rapidly answering.^^

**Comment by stormcoral** [comment]
I want to ask the jpegio library is also used in the infer code, and does it also have memory leak issues？

**Comment by stormcoral** [comment]
@qcf-568
