### ISSUE TITLE
sss

### ISSUE THREAD

**Issue by duxjsjsjs** [qcf-568/DocTamper#27]
代码怎么跑啊，我需要自己训练数据吗

**Comment by qcf-568** [comment]
推理代码可以参考这个notebookhttps://colab.research.google.com/drive/1rWaSKy2Rsy5welyvj6FbzF01o2zv8ips?usp=sharing，拿到数据和代码后运行相应命令；训练代码暂不发布，可以按照我说明进行相应配置，有问题可以问我。
