### ISSUE TITLE
Question regarding VPH and Swin for feature extraction

### ISSUE THREAD

**Issue by Shaurya026** [qcf-568/DocTamper#3]
Hi, thanks for providing the code for digital tamper detection, great work! 

I had a doubt, if the VPH and Swin layers were trained with the full dtd network end2end or they were pre-trained on image-net separately and plugged in as feature extractors? 

Had this doubt since, you were using the last three stages of swin transformer.

**Comment by qcf-568** [comment]
They were trained with the full dtd network end2end, and they were initialized with imagenet pretrained weights before training.
