### ISSUE TITLE
Invalid JPEG file structure: two SOI markers

### ISSUE THREAD

**Issue by RogerYu123** [qcf-568/DocTamper#32]
dataset里面进行数据预处理的时候，doctamper的某些图片经过多次(一般3次)压缩之后，会出现Invalid JPEG file structure: two SOI markers的报错，但目前我这边没法捕捉到该error，暂时没办法定位是哪一行代码出的问题。

**Comment by qcf-568** [comment]
您好，我这边也有这个问题，并定位到是jpegio库的问题。jpegio 库存在内存泄漏的bug未被修复，多次使用过程中内存泄漏到一定程度就会出现该报错导致进程中止。我之前每个epoch保存权重和优化器参数等，设置命令让程序中止后自动读取相应断点权重继续，来应对这种问题。

**Comment by qcf-568** [comment]
Substitute  the jpegio with jpeg2dct can solve this.

**Comment by Saillxl** [comment]
from jpeg2dct.numpy import load  
dct = load(tmp.name, False)[0]
h, w = dct.shape[:2]
dct = dct.reshape(h, w, 8, 8).transpose(0, 2, 1, 3).reshape(h * 8, w * 8).astype(np.int64)
您好，我用jpeg2dct运行一段时间还是会报[Invalid JPEG file structure: two SOI markers]这个问题

**Comment by qcf-568** [comment]
可以进行断点保存读取
