### ISSUE TITLE
请教下关于训练脚本

### ISSUE THREAD

**Issue by Mike-Xiao** [qcf-568/DocTamper#33]
您好，我目前尝试在doctamper的FCD和SCD数据集上，仿照您推荐的那个天池比赛训练方案，用SoftCrossEntropy和Diceloss作为损失函数，尝试过efficientnet_b6＋unet++和resnet101+deeplabV3进行训练，但是损失函数好像一直都没下降，f1-score也没提高，在这方面没有什么经验，想请教下可能是哪里设置有问题，应该怎么调？感谢
![image](https://github.com/qcf-568/DocTamper/assets/46700210/b0d1385e-745f-4eb8-9573-ace559f7ea2b)

**Comment by Mike-Xiao** [comment]
都使用了imagenet预训练的权重。是因为数据集的篡改痕迹很精细，这种没有使用压缩和频域信息的普通分割网络都收敛不了吗，不是很懂为什么TAT。

**Comment by qcf-568** [comment]
一般如果不用特别花里胡哨的模块，不至于收敛不了。为什么不用训练集训练而是用测试集呢？另外DocTamper这个数据集不要用DiceLoss，我提到的LovaszLoss也是那个项目里面自带的，可以先把loss function对齐一下(SoftCELoss: LovaszLoss 1:1)，直接用里面自带的那些函数。

**Comment by Mike-Xiao** [comment]
感谢！换了确实加了LovaszLoss之后前几轮有提升了！哈哈因为训练集有点大想先用小的数据集看看普通网络有没有效果来着，可以再指教一下看看我现在的这些参数有没有可以优化的地方吗，scheduler调整学习率那种工具有用吗。然后还想请教下Tsroie这个数据集训练的话有没有什么需要特别注意的地方，用什么设置比较好呢，应该缩放成多大来训练和测试。多谢多谢
![image](https://github.com/qcf-568/DocTamper/assets/46700210/ec0bb08d-0fa9-47da-ade0-d8256e3f1bea)
![image](https://github.com/qcf-568/DocTamper/assets/46700210/4c1d8d8b-7c3b-4fbc-a5ea-85e7b010009c)
![image](https://github.com/qcf-568/DocTamper/assets/46700210/e27e2015-f17a-4844-ae65-1db8cbfd3fa5)

**Comment by qcf-568** [comment]
增广里面的A.OneOf的后5个我没用到。DocTamper是batch_size12训练10epoch。TSROIE我没有缩放操作，全部是直接切块训练切块推理再合并，batch_size12训练400epoch，TSROIE用DiceLoss比LovaszLoss效果好。
