### ISSUE TITLE
Is the JPEG compression rate during training selected from the range of 100-75 or 100-88?

### ISSUE THREAD

**Issue by Rapisurazurite** [qcf-568/DocTamper#34]
For the CLTD compression, the chosen range is (100-S/T, 100), with a total of 100K iterations and T being 8192. Does this imply that the minimum compression rate is calculated as 100-(100K/8192), which equals 88?

**Comment by qcf-568** [comment]
S is the steps of total images feeding, instead of the iterations. With a total of 100K iterations with batchsize=12, S is 12*100K=1200K, instead of 100K. The lower bound of compression is cliped to 75 when it is lower than 75.

**Comment by Rapisurazurite** [comment]
Thank you, I will try it.
