### ISSUE TITLE
关于重压缩

### ISSUE THREAD

**Issue by qiyuebobo** [qcf-568/DocTamper#35]
你好，请问您在训练的时候按照q压缩了一次，在test时压缩1-3次，还是在train和test都压缩了随机1-3次

**Comment by qcf-568** [comment]
你好，训练时候的压缩次数、量化表、代码均与提供的推理代码dataloader中的情况保持一致。
推理代码与训练代码的压缩那部分的差异就是q固定变为q随机。

**Comment by qiyuebobo** [comment]
您的意思是训练的时候q是随机的，按照下面这个公式？
![image](https://github.com/qcf-568/DocTamper/assets/76613430/1321e133-692f-4172-aaaa-61bf7c80f3bd)

**Comment by qcf-568** [comment]
是的

**Comment by qiyuebobo** [comment]
您好，请问您的dct系数是预先处理好了放在了哪里，我没有在提供的代码中找到生成每张图片及其对应的dct系数的部分。
