### ISSUE TITLE
No read the compressed image

### ISSUE THREAD

**Issue by HHHuge** [qcf-568/DocTamper#36]
In line 76, the image is saved in JPEG format, and the JPEG information is read from the file (line 77). However, the RGB data is not re-read from the file.

<img width="603" alt="image" src="https://github.com/qcf-568/DocTamper/assets/109289570/0017f1ae-1a25-4352-a87f-19d74b31609c">

**Comment by qcf-568** [comment]
This might be a oversight in such script. As our model mainly rely on frequency domain clues to localize tamper, this has almost no affect on the performance and has no affect on the conclusion. The other pure RGB models in comparison may have a bit drop in performance with the extra compression.

**Comment by HHHuge** [comment]
Can you provide correct performance metrics?

**Comment by qcf-568** [comment]
I plan to update it about two or three weeks later.

**Comment by qcf-568** [comment]
After updating the final compression in both training and inference scripts, the metrics show an about 0.5 points fluctuation, which is within the normal range. So the original metrics are kept as valid ones. I'm very busy now and will upload the new model in April.
