### ISSUE TITLE
About training CATNET on Doctamper

### ISSUE THREAD

**Issue by Mike-Xiao** [qcf-568/DocTamper#37]
您好，不好意思打扰了我想再请教一下，目前我是用CATNET：https://github.com/mjkwon2021/CAT-Net 这个项目里的默认设置和训练脚本在doctamper的整个训练集和测试集上训练和测试，在训练的时候loss确实在下降，但是到测试集validate的时候，输出的那几个数值都一模一样，第一轮iou就在49.2，后面几轮就连小数都没有变过，loss也加上过lovasz但也没区别，尝试不加载预训练的RGB和DCT也差不多，我检查了一下用来验证的模型确实是更新过的，这方面不太懂感觉很奇怪，大佬可以帮忙分析一下可能是哪里出问题了吗，感谢感谢。
![image](https://github.com/qcf-568/DocTamper/assets/46700210/e780eabe-2e96-4a88-abe8-5b0e7edde2b8)
![image](https://github.com/qcf-568/DocTamper/assets/46700210/d73dd7f0-7b2c-401e-99bd-ac7a3a0b9199)
![image](https://github.com/qcf-568/DocTamper/assets/46700210/8c16037f-1e75-4654-874a-5c945b9da11b)

**Comment by HHHuge** [comment]
这是把所有像素预测为0了，所以iou测出来都一样

**Comment by HHHuge** [comment]
> > 这是把所有像素预测为0了，所以iou测出来都一样
> 
> 好的十分感谢！请教下您觉得可能应该朝哪个方向修改训练方式呢，我训练CATNET确实没什么经验，怎么改都是这样，没有什么头绪现在有点难顶Orz

我试过CATNET，改好dataset后是可以成功训练的

**Comment by Mike-Xiao** [comment]
> > > 这是把所有像素预测为0了，所以iou测出来都一样
> > 
> > 
> > 好的十分感谢！请教下您觉得可能应该朝哪个方向修改训练方式呢，我训练CATNET确实没什么经验，怎么改都是这样，没有什么头绪现在有点难顶Orz
> 
> 我试过CATNET，改好dataset后是可以成功训练的

好的，请问您就是用的CATNET里面自带的训练脚本和参数吗，我就是用的它的没做调整

**Comment by HHHuge** [comment]
> > > > 这是把所有像素预测为0了，所以iou测出来都一样
> > > 
> > > 
> > > 好的十分感谢！请教下您觉得可能应该朝哪个方向修改训练方式呢，我训练CATNET确实没什么经验，怎么改都是这样，没有什么头绪现在有点难顶Orz
> > 
> > 
> > 我试过CATNET，改好dataset后是可以成功训练的
> 
> 好的，请问您就是用的CATNET里面自带的训练脚本和参数吗，我就是用的它的没做调整

除了GPUS和END_EPOCH，其他参数没有改

**Comment by Mike-Xiao** [comment]
> > > > > 这是把所有像素预测为0了，所以iou测出来都一样
> > > > 
> > > > 
> > > > 好的十分感谢！请教下您觉得可能应该朝哪个方向修改训练方式呢，我训练CATNET确实没什么经验，怎么改都是这样，没有什么头绪现在有点难顶Orz
> > > 
> > > 
> > > 我试过CATNET，改好dataset后是可以成功训练的
> > 
> > 
> > 好的，请问您就是用的CATNET里面自带的训练脚本和参数吗，我就是用的它的没做调整
> 
> 除了GPUS和END_EPOCH，其他参数没有改

好的谢谢您，那我再查查。。那好奇怪啊。。
