### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by qiyuebobo** [qcf-568/DocTamper#38]
你好，请问您有计划释出png版本的数据集嘛，数据集中除了掩码和篡改图片之外还有其他的信息吗？dct系数是否存储在数据集中？感谢回答！

**Comment by qcf-568** [comment]
你好，dct系数没有保存在数据集中，之后我们会提供篡改类型信息。

**Comment by qcf-568** [comment]
PNG版本，直接用这个vizlmdb.py脚本for循环读取遍历保存即可，https://github.com/qcf-568/DocTamper/blob/main/vizlmdb.py。
