### ISSUE TITLE
how to implement CLTD?

### ISSUE THREAD

**Issue by KAHIMWONG** [qcf-568/DocTamper#42]

**Comment by qcf-568** [comment]
You can set a counter in the Dataset class, using it in the __getitem__ function. Each time the __getitem__ function is used, the counter add one.

**Comment by qcf-568** [comment]
Then the counter controls the compression factor in the __getitem__ function.

**Comment by qcf-568** [comment]
Another way is using the index input of the __getitem__ function, the index denotes the ordinal of the sample when "shuffle" is closed.
