### ISSUE TITLE
Specific tampering type of DocTamper Dataset

### ISSUE THREAD

**Issue by SummerLe** [qcf-568/DocTamper#43]
As shown in Table 2 of this paper, Copy-move, splicing and generation are all included, the specific number of different tampering types is clearly given, So I wonder whether the tampering type of each image is labeled?
or how does the specific number in Table 2 counted, and is there any way to redivide the dataset with tampering type?
Thanks！

**Comment by qcf-568** [comment]
I have recorded this tampering type label for each sample and will make it public. The dataset was shuffled before release. Therefore I need to map the type label to the new indexes. I'm too busy to do this now, and will release this information before  the end of April.

**Comment by qcf-568** [comment]
@SummerLe This is the required tampering type information.

https://pan.baidu.com/s/1-qb-hlb4M5M7Chbtf0uFtQ?pwd=smx9
