### ISSUE TITLE
请问数据集中是否存在组合篡改类型，以及能否提供对比的其他方法在DocTamper上训练的模型权重？

### ISSUE THREAD

**Issue by Meeeee06** [qcf-568/DocTamper#44]
数据集中的图像是否存在组合篡改类型，就是一张图像中既包括复制粘贴又包括拼接或生成类型呢？

是否可以提供论文中对比的方法在DocTamper上训练的模型权重，以便后续进行对比研究

**Comment by qcf-568** [comment]
同一张样本没有组合类型，但存在部分原始样本存在分别被多种篡改类型篡改后保存为不同样本的情况。对比方法权重是有的，但一个个整理上传比较费时费力，因此优先考虑对比方法里面性能较好的上传。其中Swin的权重我发给过sijiangmeng@qq.com，你问他要下，CAT-Net的权重我预计半年内上传。

**Comment by qcf-568** [comment]
或者我传之前存的预测结果，那个可能方便点。

**Comment by Meeeee06** [comment]
好的，谢谢回复。如果方便的话希望可以您可以上传一下之前的预测结果~
