### ISSUE TITLE
details of data augmentation

### ISSUE THREAD

**Issue by KAHIMWONG** [qcf-568/DocTamper#45]
Hi, instead of jpeg, is there any augmentation used? is the augmentation order manner (augmentations-then-jpeg or jpeg-then-augmentations)?

**Comment by qcf-568** [comment]
JPEG is the only augmentation method that works, for the DocTamper dataset.

**Comment by qcf-568** [comment]
I tried other augmentations in augmentations-then-jpeg manner, but they didn't work.
