### ISSUE TITLE
Dataset password

### ISSUE THREAD

**Issue by ah-ke** [qcf-568/DocTamper#47]
After the dataset is downloaded from Baidu Cloud, why do you need a password to decompress it? What is the password set by the author？

**Comment by qcf-568** [comment]
We have answered this question in #46 . However, this user outputs stupid questions likes a robot, and it applies for the dataset in a rude manner, without agreeing to the pure research use this dataset. Our team decides not to provide the dataset to this rude user, and ignore its issues permanently. This is the first time we have encountered this situation.

**Comment by 123sunShine1** [comment]
解释：（1）我用武大的教育邮箱申请了，但是你没给我。而是发了一个苦笑的表情。我以为你没注意到我要的是数据集密码。然后我就说了句“大哥，我要的是数据集密码”，你就拉黑我。我真没别的意思，如果你觉得"大哥"两字粗鲁了，是我的错，好吧。（2）我重复#46问题，是因为#46被系统给删除了好像，我这边看不到了。我才又补上一个，那也没必要说话这样，同样是学生，你这态度也太不礼貌了。不理解。

**Comment by qcf-568** [comment]
我上述描述你没有礼貌的原因是：
1、数据集密码申请应当先同意协议(非商用)，并私下通过邮件申请，而你这样公开直接问密码，如果回答了密码后谁都能看到，是无视贡献者的协议约定。
2、你申请数据集就五个字“数据集密码”，不仅没有表达同意非商用协议，甚至连句完整的话都没有(如下图)。我从不要求申请要写正规邮件格式，但你这个真的过分。
![2024-03-06 18-37-23屏幕截图](https://github.com/qcf-568/DocTamper/assets/128270723/057ea470-e2ff-424a-8388-02ad61d19b4e)

**Comment by qcf-568** [comment]
而你同学申请是这样的，和你的申请反差很明显
![2024-03-06 18-38-30屏幕截图](https://github.com/qcf-568/DocTamper/assets/128270723/b75dd4ac-3818-4799-a1dc-32af0c5ebd0f)

**Comment by qcf-568** [comment]
其他人的申请大多是这样的，反差更为明显
![2024-03-06 18-39-29屏幕截图](https://github.com/qcf-568/DocTamper/assets/128270723/1f43d08a-9f8b-4489-a822-30042ffd1a07)

**Comment by 123sunShine1** [comment]
你的话，让我终于知道你生气的点了。原来是“数据集密码”啊，我我我确实没想到是这。在这句话之前，我也礼貌问基线模型的权重是否能分享一下。然后，我还想知道一下数据集解码的密码。就直接先发了个这几个字，我确没有再问下一个问题是，再那么正式化的客气咨询。好吧，在这里我诚恳为自己没有客气询问表达歉意。

**Comment by 123sunShine1** [comment]
![微信图片_20240306200547](https://github.com/qcf-568/DocTamper/assets/162436798/1dee1ef5-739e-490d-a968-1333de8d7085)

**Comment by 123sunShine1** [comment]
在那句话之前，我不是已经礼貌的问过问题了吗？后面又聊了几句，再问新的问题还需要像开始那样官方吗？
![Uploading 微信图片_20240306200547.jpg…]()

**Comment by 123sunShine1** [comment]
![微信图片_20240306200547](https://github.com/qcf-568/DocTamper/assets/162436798/458c1ce4-22b3-4bf0-a41e-0dcae0ca4a93)

**Comment by qcf-568** [comment]
这些问题我都礼貌地回答过了。因为你要我加你微信我没同意，所以你才会开启新一轮对话并故意那样没礼貌地发邮件。申请密码的邮件显然是新的对话。
![2024-03-06 20-42-45屏幕截图](https://github.com/qcf-568/DocTamper/assets/128270723/777c3e31-eebd-4468-91ec-da5b17c94fbf)

**Comment by qcf-568** [comment]
而且，你明知数据集密码需要先同意协议后申请的情况下，你不仅没有表示同意协议反而还公开询问密码，明显是对贡献者的不礼貌。

**Comment by 123sunShine1** [comment]
大哥，你有毒吧。你好歹把我微信打个马赛克啊。你这不带这么攻击人的吧？我都没指名道心

**Comment by 123sunShine1** [comment]
大哥，哪有同意协议啊，你这是和杠上了是吧。别人不是询问吗，我真的是想打你

**Comment by 123sunShine1** [comment]
你有要求可以提出来啊，莫名其妙就拉黑邮件。我都不知道你生啥气，这会跟我较劲。你是直男吗
