### ISSUE TITLE
有关训练和测试压缩因子的问题

### ISSUE THREAD

**Issue by szjyoo** [qcf-568/DocTamper#49]
作者您好，我想向您请教如下问题：
1、训练过程中图片的压缩因子应当如何选取
2、测试过程中图片最后不需要以q为质量因子压缩一次吗（代码中图片压缩存入了temp中但是没有保存）
![a6bba803b050451184f191c75fde6c0](https://github.com/qcf-568/DocTamper/assets/164048533/500ac326-2452-4ec1-b3df-013e861ee3b5)
3、我使用了您提供的代码和权重在DocTamper上进行了测试，在压缩因子为75仅压缩一次的情况下，P R F分别为0.588 0.487 0.533，相较压缩因子在75-100之间选取、压缩1到3次的情况有所下降，请问这是正常现象吗

**Comment by qcf-568** [comment]
您好：
1、训练过程压缩因子根据CLTD公式随机采样得到。
2、目前接口就是这样的，不打算修改。若修改，训练与推理代码对齐后仅有小与1可忽略的指标抖动，对结论均无影响。
3、只有75压缩，比75~100随机压缩指标低是正常的。
