### ISSUE TITLE
Where does it save the inference results? That is the regions where the tampering is there in document.

### ISSUE THREAD

**Issue by ayaan-mphasis** [qcf-568/DocTamper#5]

**Comment by qcf-568** [comment]
You can adjust some of the codes, save the results as images before evaluation.

**Comment by ayaan-mphasis** [comment]
@qcf-568 Could you point me to the files where I would have to make changes exactly if possible? Thanks.

**Comment by qcf-568** [comment]
@ayaan-mphasis Yes, to visualize the prediction masks, you can add some codes to eval_dtd.py, e.g. below L216 of eval_dtd.py:

for p in pred:
    cv2.imwrite('xxx.jpg', (p*255).astype(np.uint8))

Thanks!

**Comment by ayaan-mphasis** [comment]
Thanks! @qcf-568 Just one last thing. How can i do this on a custom document image of my own?

**Comment by qcf-568** [comment]
Crop the whole image into patches, inference with the patches and combine the result. You can refer to L39~L137 of https://github.com/qcf-568/DocTamper/blob/main/models/tsroie/infer_sroie.py. It's notable that the provided models didn't consider the edge padding, I suggest fine-tuning them with patches with edge padding.
