### ISSUE TITLE
loss

### ISSUE THREAD

**Issue by Saillxl** [qcf-568/DocTamper#52]
作者你好，打扰一下。在訓練過程中，我發現loss在十個epoch中均維持在0.92左右 請問這是什麽原因呢？

**Comment by qcf-568** [comment]
正常现象，Lovasz Loss占大部分贡献。

**Comment by Saillxl** [comment]
感謝您的及時回復，不太理解的是loss爲什麽一直不下降？是sce下降lovaszloss上升還是？

**Comment by qcf-568** [comment]
也都在下降，但是下降的不太明显

**Comment by Saillxl** [comment]
哦哦，感謝
