### ISSUE TITLE
 Requesting Guidance on Running Model on Local Machine

### ISSUE THREAD

**Issue by Nomiluks** [qcf-568/DocTamper#54]
I'm quite impressed with the work you've done! 

I'm interested in testing out your model on my local machine with a sample image. Could you please provide guidance on the steps I need to follow to accomplish this?

Thank you

**Comment by qcf-568** [comment]
Please refer to L39~L137 https://github.com/qcf-568/DocTamper/blob/main/models/tsroie/infer_sroie.py​

and this colab notebook https://colab.research.google.com/drive/1rWaSKy2Rsy5welyvj6FbzF01o2zv8ips?usp=sharing
