### ISSUE TITLE
请问推理代码是哪个呢？

### ISSUE THREAD

**Issue by sunyclj** [qcf-568/DocTamper#55]

**Comment by sunyclj** [comment]
> _No description provided._

测试数据也必须是lmdb格式？？

**Comment by qcf-568** [comment]
DocTamper的LMDB推理代码 https://github.com/qcf-568/DocTamper/blob/main/models/eval_dtd.py
T-SROIE的JPG整图推理代码 https://github.com/qcf-568/DocTamper/blob/main/models/tsroie/infer_sroie.py
