### ISSUE TITLE
关于在DocTamper上训练CAT-Net

### ISSUE THREAD

**Issue by szjyoo** [qcf-568/DocTamper#57]
作者您好，我尝试在DocTamper上训练CAT-Net，代码链接为https://github.com/mjkwon2021/CAT-Net ，我使用的训练代码是CAT-Net中的训练脚本，DocTamper训练数据集中的图片我采用了1到3次的随机质量因子压缩（75-100），120000张数据集划分为110000张训练集和10000张验证集，但是我复现出的结果为P:0.622 R:0.696 F:0.657,这与您论文中给出的指标有些差距，请问您有什么建议吗？

**Comment by qcf-568** [comment]
论文中最终汇报的实验结果是基于各模型公平一致的初始化与训练流程实现的，训练策略及初始化(e.g., 应仅使用ImageNet预训练权重)的差异及不公正等会导致指标差异。

**Comment by qcf-568** [comment]
若对训练脚本存在疑问，可以通过教育邮箱申请查看关键片段。
