### ISSUE TITLE
关于评价指标

### ISSUE THREAD

**Issue by qiyuebobo** [qcf-568/DocTamper#58]
作者你好：
  请问您在实验的时候用到的pre、iou等指标都是默认miou、mpre吗?
  在您提供的测试代码中输出是meaniou：
class IOUMetric:
    def __init__(self, num_classes=10):
        self.num_classes = num_classes
        self.hist = np.zeros((num_classes, num_classes))
    def _fast_hist(self, label_pred, label_true):
        mask = (label_true >= 0) & (label_true < self.num_classes)
        hist = np.bincount(
            self.num_classes * label_true[mask].astype(int) +
            label_pred[mask], minlength=self.num_classes ** 2).reshape(self.num_classes, self.num_classes)
        return hist
    def add_batch(self, predictions, gts):
        for lp, lt in zip(predictions, gts):
            self.hist += self._fast_hist(lp.flatten(), lt.flatten())
    def evaluate(self):
        acc = np.diag(self.hist).sum() / self.hist.sum()
        acc_cls = np.diag(self.hist) / self.hist.sum(axis=1)
        acc_cls = np.nanmean(acc_cls)
        iu = np.diag(self.hist) / (self.hist.sum(axis=1) + self.hist.sum(axis=0) - np.diag(self.hist))
        mean_iu = np.nanmean(iu)
        freq = self.hist.sum(axis=1) / self.hist.sum()
        fwavacc = (freq[freq > 0] * iu[freq > 0]).sum()
        return acc, acc_cls, iu, mean_iu, fwavacc

**Comment by qcf-568** [comment]
评价指标是前景IoU、前景Pre、前景F1，而非前景背景平均指标。这里面虽然输出了mean_iu，但实际用的只有iu而非mean_iu. 这个IoU评价指标是在前人项目里面直接拿的https://github.com/DLLXW/data-science-competition/blob/main/tianchi/ImageForgeryLocationChallenge/utils/metric.py，这个应该也是FCN的官方评价指标。

**Comment by qcf-568** [comment]
参考第218行和第221行 of https://github.com/qcf-568/DocTamper/blob/main/models/eval_dtd.py
