### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 556) exited unexpectedly

### ISSUE THREAD

**Issue by stormcoral** [qcf-568/DocTamper#59]
After training for two epochs, an error as described in the question occurs. How can this be resolved？ @qcf-568

**Comment by stormcoral** [comment]
RuntimeError: DataLoader worker (pid 556) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

**Comment by qcf-568** [comment]
please see #32 
replace jpegio with jpeg2dct:

from jpeg2dct.numpy import load
dct =  load(tmp.name,False)[0]
h,w = dct.shape[:2]
dct = dct.reshape(h,w,8,8).transpose(0,2,1,3).reshape(h*8,w*8).astype(np.int64)

**Comment by stormcoral** [comment]
> please see #32 replace jpegio with jpeg2dct:
> 
> from jpeg2dct.numpy import load dct = load(tmp.name,False)[0] h,w = dct.shape[:2] dct = dct.reshape(h,w,8,8).transpose(0,2,1,3).reshape(h_8,w_8).astype(np.int64)

If I switch to this library, how do I calculate the image's quantization tables, which is referred to as use_qtb2 in the code?

**Comment by stormcoral** [comment]
@qcf-568

**Comment by qcf-568** [comment]
@stormcoral for quantization tables, the same as the original code.
