### ISSUE TITLE
图片和标签问题

### ISSUE THREAD

**Issue by Iloccorb96** [qcf-568/DocTamper#64]
不好意思问题有点多...
如下图，这个ps的技术是什么呀，能否告知一下如何ps的，因为我完全看不出如何篡改的，篡改后的内容，毫无字体、颜色、间隔、纹理上的异常，语义也是通顺的...
![image](https://github.com/user-attachments/assets/1aad520d-efd3-450e-94fb-978330e7bb4b)
![label](https://github.com/user-attachments/assets/5c142d95-7a86-4dd0-b65a-63b91d971c50)

**Comment by qcf-568** [comment]
因数据规模庞大，单拿出一张图无法确定具体篡改流程，但**数据集图片肯定是篡改图片且标注无误。证据是能够正常拟合，用其他数据训练好后，在最简单的无压缩模式下能推理出与GT相近结果**，这一点是制作数据过程中经过反复确认的。如果是未篡改图片则无法正常拟合且无法推理得到相近结果。

**Comment by Iloccorb96** [comment]
好的，确实要为这个ps技术点赞...真看不出来，一度怀疑是不是有问题

**Comment by dc6273632** [comment]
作者你好，我把DocTamper数据集所有图片和mask都导出来了，然后发现确实有很多图片和标签对应不上，有些很明显有篡改的图片，标签里显示没有篡改。我取了测试集的image-000000001.jpg和label-000000001.png，你看一下。

![Image](https://github.com/user-attachments/assets/2e9ebc50-9d1e-4aff-b191-0633946ab759)
<img width="512" height="512" alt="Image" src="https://github.com/user-attachments/assets/9b3609c4-2d2f-4966-8a08-16432c72096a" />

**Comment by qcf-568** [comment]
@dc6273632 标签是绝对正确的，请按非0即为篡改区域并255显示，你这里mask是黑的因为篡改区域的gt是1比较暗，你乘255再看就知道了
