### ISSUE TITLE
ModuleNotFoundError: No module named 'dtd'

### ISSUE THREAD

**Issue by stormcoral** [qcf-568/DocTamper#65]
@qcf-568 类的初始化和返回错误信息如下，在其他代码中进行类的实例化ps_model = PS_Detect(args)之后，会报ModuleNotFoundError: No module named 'dtd'的错误。看错误信息是self.vph = torch.load(vph_pt)的问题，想问下这个问题如何解决呢？
类的初始化：
 def __init__(self, args):  
        self.args = args
        self.model = seg_dtd(self.args).to(self.args.device)
        self.loader = torch.load(self.args.weight_path,map_location='cpu')['state_dict']
        self.model.load_state_dict(self.loader)
        self.model.eval()

完整报错信息：
   ps_model = PS_Detect(args)
  File "D:\project\ps_det\code\ps_service\src\.\services\ps_det.py", line 24, in __init__
    self.model = seg_dtd(self.args).to(self.args.device)
  File "D:\project\ps_det\code\ps_service\src\.\services\dtd.py", line 344, in __init__
    self.model = DTD(args)
  File "D:\project\ps_det\code\ps_service\src\.\services\dtd.py", line 320, in __init__
    self.vph = torch.load(vph_pt)
  File "D:\anaconda3\envs\torch1.10\lib\site-packages\torch\serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\anaconda3\envs\torch1.10\lib\site-packages\torch\serialization.py", line 882, in _load
    result = unpickler.load()
  File "D:\anaconda3\envs\torch1.10\lib\site-packages\torch\serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'dtd'

**Comment by qcf-568** [comment]
你好，将dtd.py、vph.pt与运行主函数放在主目录下即可

**Comment by stormcoral** [comment]
@qcf-568 感谢。这个问题解决后又报了另一个错误AttributeError: Can't get attribute 'BasicLayer' on <module '__main__' from '/opt/conda/bin/gunicorn'>，我把swins.py放在和dtd.py同一级目录后，没有解决这个问题。

**Comment by qcf-568** [comment]
你好，这个报错是因为，加载vph.pt的脚本里面没有BasicLayer的实现，而这个实现在swins.py里面。解决方案就是在加载vph.pt的脚本里面以及主函数里面加入例如from swins import *，同时确保swins.py路径正确这一行能运行。

**Comment by qcf-568** [comment]
你好，代码有网络结构定义但是报错是Pytorch的机制问题，通过torch.save直接保存的模型都需要在加载脚本中包含类定义。如果在部署环境中需要避免类定义的使用，考虑到该模型输入分辨率固定 通过切块合并实现任意尺度推理，可以先在单独项目中通过单独脚本将已完成训练的模型利用torch.jit.script或torch.jit.trace保存为无外部依赖的权重 [参考](https://blog.csdn.net/m0_70885101/article/details/131498340)，后直接在部署环境中通过torch.jit.load加载使用。

**Comment by stormcoral** [comment]
了解了，感谢！

**Comment by stormcoral** [comment]
> 你好，代码有网络结构定义但是报错是Pytorch的机制问题，通过torch.save直接保存的模型都需要在加载脚本中包含类定义。如果在部署环境中需要避免类定义的使用，考虑到该模型输入分辨率固定 通过切块合并实现任意尺度推理，可以先在单独项目中通过单独脚本将已完成训练的模型利用torch.jit.script或torch.jit.trace保存为无外部依赖的权重 [参考](https://blog.csdn.net/m0_70885101/article/details/131498340)，后直接在部署环境中通过torch.jit.load加载使用。

了解了，感谢！
