### ISSUE TITLE
请教training set中的纯黑label图片

### ISSUE THREAD

**Issue by licho123** [qcf-568/DocTamper#66]
看到不少纯黑的图片里面 他们的max value有1或者2，为什么不是0呢？我理解这种label表示对应的img图片都是真实图片（没有经过纂改处理的），不知道理解是否正确？

img = cv2.imread(f)
print(f"shape: {img.shape} max: {img.max()} min : {img.min()}")

shape: (512, 512, 3) max: 2 min : 0
shape: (512, 512, 3) max: 2 min : 0
shape: (512, 512, 3) max: 1 min : 0
shape: (512, 512, 3) max: 2 min : 0
shape: (512, 512, 3) max: 2 min : 0
shape: (512, 512, 3) max: 2 min : 0
shape: (512, 512, 3) max: 2 min : 0
shape: (512, 512, 3) max: 2 min : 0
shape: (512, 512, 3) max: 2 min : 0

**Comment by changchaoqun** [comment]
max值1是因为有的图片做了二值化，所以可视化时候1*255，转为了mask图，至于为什么有2 很奇怪，我在存图的时候没看到，max要么255或则1，脚本vizlmdb.py
![1724137154870](https://github.com/user-attachments/assets/1ac4f26b-6321-4683-b3bc-455888ce9ea9)
