### ISSUE TITLE
How to train the model with a different input size ?

### ISSUE THREAD

**Issue by PhmHiu** [qcf-568/DocTamper#68]
Hi, I want to train the model with a different input size, not 512. Can you tell me how I can do this?

I am trying to use images with a different input size but it gets errors in swin transformer

**Comment by PhmHiu** [comment]
![Untitled](https://github.com/user-attachments/assets/1db2fa03-b60d-4ce4-bb99-872333be8fe8)
Here is the detailed error

**Comment by qcf-568** [comment]
I tried training the model with input size=768*768 and the code worked. My guess is that your input size is not a squire or an integer multiple of 64, which are required for the swin-transformer. It's worth noting that resizing is forbidden during training, only crop and padding will work. If you have difficulty reproducing the training code, you can ask me for some code via your educational email.

**Comment by PhmHiu** [comment]
I have tried and the model only works if the input size is a multiple of 256 (eg: 256, 512, 768, ...). But when I trained the model with input size = 320 x 320, it fails

**Comment by qcf-568** [comment]
You can also replace the swin-transformer with other backbones such as convnext.
