### ISSUE TITLE
Request for Training and Data Synthesis Code

### ISSUE THREAD

**Issue by reese0621** [qcf-568/DocTamper#79]
Hello qcf-568,

I hope you're doing well. As per your request, I sent an email from my .edu address to request access to the unreleased code. I wanted to follow up here to ensure my email was received. Please let me know if there are further steps I should take to access the resources.

Thank you for your time!

Reese

**Comment by qcf-568** [comment]
Hello, thank you for your attention!
My previous email address doesn't work, please re-send the email to the new address updated in Readme.md, thank you!

**Comment by qcf-568** [comment]
Dear Reese,
I wonder if this is your email name, I have replied this email with the same question within 12 hours.
![screenshot_2024-12-03_15-49-29](https://github.com/user-attachments/assets/050d4c59-c2fe-41a3-9573-e6cf2f70cafb)
If this is not your email name, I has checked all my email box and I'm sure the email is not received, please re-send the email to 202221012612@mail.scut.edu.cn.

**Comment by reese0621** [comment]
Dear Chenfan,

Thank you for your prompt response! I believe the email name "symonsm" does match my email, but the subject line may differ, as I sent the email with the subject "Request for Access to DocTamper Training and Data Synthesis Code."

I’ve double-checked both my inbox and junk folder, but I wasn’t able to locate your reply. If it’s not too much trouble, could you kindly resend the email? Please also notify me through GitHub issues after resending it so I can check if I’ve received it this time.

Thank you again for your time and assistance!

Best regards,

Reese

**Comment by qcf-568** [comment]
Dear Reese,

I’ve double-checked both my inbox and junk folder, but I wasn’t able to find your email. I can send you the required code but I don't know the target email address.
**So please provide your email address and I will send the code to you.**

Thank you again for your time!

Best regards,

Chenfan

**Comment by qcf-568** [comment]
![image](https://github.com/user-attachments/assets/25d90138-08fe-4829-abfc-07b781d54433)
This is the previous email with address "symonsm@nwfsc.edu", which I've replied within 12 hours. I find the name exactly matches yours!

**Comment by qcf-568** [comment]
I've re-send the above two reply emails to "symonsm@nwfsc.edu". Previously, these two emails are also sent to "symonsm@nwfsc.edu".

**Comment by reese0621** [comment]
Dear Chenfan,

Thank you for your response! Unfortunately, I still haven’t been able to receive your replies, and I suspect this might be due to my university email system blocking messages from certain external domains. For future email correspondence, could you kindly send the messages to my personal email address provided in my most recent email? I appreciate your understanding and assistance!

Best regards,

Reese
